// Code generated by protoc-gen-gogo. DO NOT EDIT.
package proto

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Probe struct {
	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Tos       []byte `protobuf:"bytes,2,opt,name=tos,proto3" json:"tos,omitempty"`
	Sent      uint64 `protobuf:"varint,3,opt,name=sent,proto3" json:"sent,omitempty"`
	Rcvd      uint64 `protobuf:"varint,4,opt,name=rcvd,proto3" json:"rcvd,omitempty"`
	Rtt       uint64 `protobuf:"varint,5,opt,name=rtt,proto3" json:"rtt,omitempty"`
	Lost      bool   `protobuf:"varint,6,opt,name=lost,proto3" json:"lost,omitempty"`
	Padding   []byte `protobuf:"bytes,7,opt,name=padding,proto3" json:"padding,omitempty"`
}

func (m *Probe) Reset()                    { *m = Probe{} }
func (m *Probe) String() string            { return proto.CompactTextString(m) }
func (*Probe) ProtoMessage()               {}
func (*Probe) Descriptor() ([]byte, []int) { return fileDescriptorLlama, []int{0} }

func (m *Probe) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Probe) GetTos() []byte {
	if m != nil {
		return m.Tos
	}
	return nil
}

func (m *Probe) GetSent() uint64 {
	if m != nil {
		return m.Sent
	}
	return 0
}

func (m *Probe) GetRcvd() uint64 {
	if m != nil {
		return m.Rcvd
	}
	return 0
}

func (m *Probe) GetRtt() uint64 {
	if m != nil {
		return m.Rtt
	}
	return 0
}

func (m *Probe) GetLost() bool {
	if m != nil {
		return m.Lost
	}
	return false
}

func (m *Probe) GetPadding() []byte {
	if m != nil {
		return m.Padding
	}
	return nil
}

func (*Probe) XXX_MessageName() string {
	return "llama.Probe"
}
func init() {
	proto.RegisterType((*Probe)(nil), "llama.Probe")
}
func (m *Probe) Marshal() (dAtA []byte, err error) {
	size := m.ProtoSize()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Probe) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Signature) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintLlama(dAtA, i, uint64(len(m.Signature)))
		i += copy(dAtA[i:], m.Signature)
	}
	if len(m.Tos) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintLlama(dAtA, i, uint64(len(m.Tos)))
		i += copy(dAtA[i:], m.Tos)
	}
	if m.Sent != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintLlama(dAtA, i, uint64(m.Sent))
	}
	if m.Rcvd != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintLlama(dAtA, i, uint64(m.Rcvd))
	}
	if m.Rtt != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintLlama(dAtA, i, uint64(m.Rtt))
	}
	if m.Lost {
		dAtA[i] = 0x30
		i++
		if m.Lost {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.Padding) > 0 {
		dAtA[i] = 0x3a
		i++
		i = encodeVarintLlama(dAtA, i, uint64(len(m.Padding)))
		i += copy(dAtA[i:], m.Padding)
	}
	return i, nil
}

func encodeVarintLlama(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Probe) ProtoSize() (n int) {
	var l int
	_ = l
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovLlama(uint64(l))
	}
	l = len(m.Tos)
	if l > 0 {
		n += 1 + l + sovLlama(uint64(l))
	}
	if m.Sent != 0 {
		n += 1 + sovLlama(uint64(m.Sent))
	}
	if m.Rcvd != 0 {
		n += 1 + sovLlama(uint64(m.Rcvd))
	}
	if m.Rtt != 0 {
		n += 1 + sovLlama(uint64(m.Rtt))
	}
	if m.Lost {
		n += 2
	}
	l = len(m.Padding)
	if l > 0 {
		n += 1 + l + sovLlama(uint64(l))
	}
	return n
}

func sovLlama(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozLlama(x uint64) (n int) {
	return sovLlama(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Probe) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLlama
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Probe: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Probe: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLlama
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthLlama
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tos", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLlama
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthLlama
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tos = append(m.Tos[:0], dAtA[iNdEx:postIndex]...)
			if m.Tos == nil {
				m.Tos = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sent", wireType)
			}
			m.Sent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLlama
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Sent |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rcvd", wireType)
			}
			m.Rcvd = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLlama
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rcvd |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rtt", wireType)
			}
			m.Rtt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLlama
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Rtt |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Lost", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLlama
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Lost = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Padding", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLlama
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthLlama
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Padding = append(m.Padding[:0], dAtA[iNdEx:postIndex]...)
			if m.Padding == nil {
				m.Padding = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLlama(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLlama
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLlama(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLlama
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLlama
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLlama
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthLlama
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowLlama
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipLlama(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthLlama = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLlama   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("github.com/dropbox/llama/proto/llama.proto", fileDescriptorLlama) }

var fileDescriptorLlama = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4f, 0x29, 0xca, 0x2f,
	0x48, 0xca, 0xaf, 0xd0, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0xcf, 0xc9, 0x49, 0xcc, 0x4d, 0x84,
	0x90, 0x7a, 0x60, 0x11, 0x21, 0x56, 0x30, 0x47, 0x69, 0x3e, 0x23, 0x17, 0x6b, 0x40, 0x51, 0x7e,
	0x52, 0xaa, 0x90, 0x0c, 0x17, 0x67, 0x71, 0x66, 0x7a, 0x5e, 0x62, 0x49, 0x69, 0x51, 0xaa, 0x04,
	0xa3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x42, 0x40, 0x48, 0x80, 0x8b, 0xb9, 0x24, 0xbf, 0x58, 0x82,
	0x09, 0x2c, 0x0e, 0x62, 0x0a, 0x09, 0x71, 0xb1, 0x14, 0xa7, 0xe6, 0x95, 0x48, 0x30, 0x2b, 0x30,
	0x6a, 0xb0, 0x04, 0x81, 0xd9, 0x20, 0xb1, 0xa2, 0xe4, 0xb2, 0x14, 0x09, 0x16, 0x88, 0x18, 0x88,
	0x0d, 0xd2, 0x59, 0x54, 0x52, 0x22, 0xc1, 0x0a, 0x16, 0x02, 0x31, 0x41, 0xaa, 0x72, 0xf2, 0x8b,
	0x4b, 0x24, 0xd8, 0x14, 0x18, 0x35, 0x38, 0x82, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0x82, 0xc4,
	0x94, 0x94, 0xcc, 0xbc, 0x74, 0x09, 0x76, 0xb0, 0x1d, 0x30, 0xae, 0x93, 0xc8, 0x89, 0x47, 0x72,
	0x8c, 0x17, 0x1e, 0xc9, 0x31, 0x3e, 0x78, 0x24, 0xc7, 0xb0, 0xe0, 0xb1, 0x1c, 0xe3, 0x89, 0xc7,
	0x72, 0x8c, 0x49, 0x6c, 0x60, 0x5f, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x01, 0x3c,
	0x74, 0xe8, 0x00, 0x00, 0x00,
}
